### ISSUE TITLE
生成的dao文件表名称后面多了个s

### ISSUE THREAD

**Issue by chrrg** [yuzd/ktormgen#2]
生成的dao文件
表名是user，但是生成的orm下的文件表名末尾出来多了个s
出错的地方：
object UserDao : Table<User>("users"){}
正确应该是
object UserDao : Table<User>("user"){}

错误时运行报错：
db.database.from(UserDao).select().rowSet.size()
报错
Exception in thread "main" java.sql.SQLSyntaxErrorException: Table 'bit.users' doesn't exist
把末尾的s删除后程序正常

**Comment by yuzd** [comment]
我看看

**Comment by yuzd** [comment]
晚上回家看下，开发环境在家里的电脑

**Comment by yuzd** [comment]
已经提交了新的版本。目前正在审核中，你也可以直接下载
链接：https://pan.baidu.com/s/1LA3oB4rQJqQmV1hZ81ZLrA 
提取码：lmnd
