### ISSUE TITLE
你好，请问在生成Dao和Model的时候可以把字段名称 下划线转驼峰吗

### ISSUE THREAD

**Issue by ghost** [yuzd/ktormgen#3]

**Comment by yuzd** [comment]
我看看

**Comment by ghost** [comment]
感谢，插件很好用

**Comment by yuzd** [comment]
周末我搞下哈

**Comment by yuzd** [comment]
plugin已更新 插件市场正在审核。

也可以手动下载安装

链接：https://pan.baidu.com/s/1nIOod5-B94KDqpuRcf7rNQ 
提取码：nrj1

**Comment by yuzd** [comment]
![image](https://dimg04.c-ctrip.com/images/0v510120008v3n6640102.png)
