### ISSUE TITLE
请问可否计划开源 AntDataCodeGen 包及外键等相关问题

### ISSUE THREAD

**Issue by Yi-pixel** [yuzd/ktormgen#4]
## 请问可否有计划 AntDataCodeGen 包
看到历史 issues 中有提到使用驼峰命名，但是是大驼峰的（期待可配置小驼峰），最终找到模板最终是由 AntDataCodeGen 生成的，所以想请问此包是否有计划开源。

看到 NuGet 页面指向的仓库是 AntData.ORM ，但未在此仓库中看到有相关代码 😮

## 配置非自动生成外键关联
另外可否配置不自动生成外键关联，目前外键关联还存在缺陷，会存在重复的外键关联属性被创建。

## bigint 类型错误
bigint 类型的字段会被解析为 ULong ，但是没有此类型。

**Comment by yuzd** [comment]
1. 驼峰命名，但是是大驼峰的（期待可配置小驼峰）
可否 举个例子，我可以优化下
(这个AntDataCodeGen 代码生成器 暂未有开源计划)

2. 外键关联这块目前是读配置的，外键功能的确不是很完善。
不使用外键功能的话，不配置SetFkList应该就可以了

3.  bigint 类型的字段 变成了ULong，是不是你选择了Unsigned?
![image](https://images4.c-ctrip.com/target/0zb5l120008xn75tzDD6E.png)

选择了Unsigned的话确实会变成这样的。感谢反馈 我修复下

**Comment by Yi-pixel** [comment]
> 1. 驼峰命名，但是是大驼峰的（期待可配置小驼峰）
>    可否 举个例子，我可以优化下
>    (这个AntDataCodeGen 代码生成器 暂未有开源计划)
> 2. 外键关联这块目前是读配置的，外键功能的确不是很完善。
>    不使用外键功能的话，不配置SetFkList应该就可以了
> 3. bigint 类型的字段 变成了ULong，是不是你选择了Unsigned?
>    ![image](https://camo.githubusercontent.com/02842b659e568f8c6c0b31aa3d5dd55f3cebf8f7d118cc628cdf6ec1bc0f39dd/68747470733a2f2f696d61676573342e632d63747269702e636f6d2f7461726765742f307a62356c313230303038786e3735747a444436452e706e67)
> 
> 选择了Unsigned的话确实会变成这样的。感谢反馈 我修复下

1、现在的驼峰是这样的如 `product_id` 字段，最终生成的是 `ProductId` ，期待添加支持 `productId` ，即首个单词为小写。

2、外键这个参数 SetFkList  在我这里是空的，但是还是会生成 😥，是需要删掉这个字段吗？

3、看起来应该是这样，因为我数据库的确是这样选的 unsigned ，我一般都会选择 unsigned ，因为 signed 的情况较少。

**Comment by yuzd** [comment]
ok 这些问题我会尽快搞下

**Comment by Yi-pixel** [comment]
> ok 这些问题我会尽快搞下

好的，感谢 💯

**Comment by yuzd** [comment]
@Yi-pixel 外键这块有啥建议吗

**Comment by Yi-pixel** [comment]
> @Yi-pixel 外键这块有啥建议吗

我这边遇到的外键是这样的，如 product 表有 created_by 和 edited_by 这两个字段都是关联到 users 表的话，就会在 user 的模型里面生成两个 Product 外键字段，但是他们生成的属性名字是一样的。同样在 Product 中生成的 edited_by 和 created_by 也是生成了 User 外键字段，他们的属性名是一样的也就造成了重复。


在业务上看来，从 Product 的 edited_by 和 created_by 关联到用户是比较常见的，可以直接使用字段名字的驼峰，如 createdBy 和 editedBy 。

但是 User 模型在这里可能就不一定需要关联到 Product 去。

可以考虑在生成外键配置那里填写表名称，仅生成已填写的，如上面的例子，就填入 SetFkList = ["product"] 这样就仅生成 Product -> User ，而不生成反向的（即不在 User 中生成）。

可以添加复杂规则，如 `SetFkList = [{"table":"user","fk":["product.created_by"]}]` 这样在 User 中生成 `val ProductCreatedBy : Product` 的外键关联

**Comment by yuzd** [comment]
配置改变不生效，外键重复的问题 和 驼峰首字母小写的问题 已解决。另外目前只支持了一对一，而且你配置了才会生成，比如user表有两个字段关联system_users表，按照下面配置只会生成user表，不会反向也生成system_users表。

![image](https://dimg04.c-ctrip.com/images/0v501120008xvgtotDB8A.png)

![image](https://dimg04.c-ctrip.com/images/0v503120008xvg8tzF9D1.png)

![image](https://dimg04.c-ctrip.com/images/0v51z120008xvgtftAE3A.png)

已上传2.3版本。正在审核

![image](https://dimg04.c-ctrip.com/images/0v54v120008xvgsy42E86.png)
